export const SIGN_IN = 'SIGN_IN';

export const SIGN_OUT = 'SIGN_OUT';

export const LOAD_RELEASES_REQUEST = 'LOAD_RELEASES_REQUEST';

export const LOAD_RELEASES_SUCCESS = 'LOAD_RELEASES_SUCCESS';

export const LOAD_RELEASES_FAILURE = 'LOAD_RELEASES_FAILURE';

export const SELECT_RELEASE = 'SELECT_RELEASE';

export const UPDATE_SELECTED_RELEASE_REQUEST =
    'UPDATE_SELECTED_RELEASE_REQUEST';

export const UPDATE_SELECTED_RELEASE_SUCCESS =
    'UPDATE_SELECTED_RELEASE_SUCCESS';

export const UPDATE_SELECTED_RELEASE_FAILURE =
    'UPDATE_SELECTED_RELEASE_FAILURE';
